language: objective-c
osx_image: xcode9.3
xcode_sdk: iphonesimulator11.0

before_install:
  - set -o pipefail
  - brew upgrade carthage || true

before_script:
  - carthage bootstrap --platform iOS --no-use-binaries --cache-builds
  - carthage build --platform iOS --no-use-binaries --cache-builds

script:
  - xcodebuild -project CFoundry.xcodeproj -scheme "CFoundry iOS" -destination "platform=iOS Simulator,name=iPhone SE" build-for-testing test | xcpretty
