language: objective-c

osx_image: xcode9.3
xcode_sdk: iphonesimulator
xcode_workspace: CF Apps.xcworkspace
xcode_scheme: CF Apps

before_install:
  - set -o pipefail
  - brew install carthage || true
  - gem install xcpretty-travis-formatter --no-rdoc --no-ri --no-document --quiet

before_script:
  - carthage bootstrap --platform iOS --no-use-binaries --cache-builds

script:
  - xcodebuild -workspace CF\ Apps.xcworkspace -scheme CF\ Apps -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone SE' build test

after_success:
  - sleep 5
